const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const operationButtons = document.querySelector('[data-equals]')
const operationButtons = document.querySelector('[data-delete]')
const operationButtons = document.querySelector('[data-all-clear]')
const previousOperandTextElement = document.querySelector('[data-equals]')
const currentOperandTextElement = document.querySelector('[data-equals]')
